
query_test = """SELECT * FROM deal LIMIT 10"""
query2 = """SELECT * FROM users WHERE user_id = %s AND user_pwd = %s"""
query5_1 = """SELECT instrument_id FROM instrument WHERE instrument_name = %s;"""
query5_2 = """SELECT counterparty_id FROM counterparty WHERE counterparty_name = %s;"""
query5_3 = """INSERT INTO deal(deal_time, deal_counterparty_id, deal_instrument_id, deal_type, deal_amount, deal_quantity) VALUES (%s, %d, %d, %s, %f, %d);"""
query7 = """ """
query8 = """ """
query9 = """ """
query10 = """ """
